version: '3.8'

services:
  postgres-otus-db:
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /tmp

  otus-highload-hw1:
    image: recvezitor/otus-highload-hw1:latest
    depends_on:
      - postgres-otus-db
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgresql://host.docker.internal:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres