###
GET {{protocol}}{{host}}/q/health

###
GET {{protocol}}{{host}}/q/info

###
POST {{protocol}}{{host}}/user/register
Content-Type: application/json

{
  "first_name": "fff1",
  "second_name": "fff",
  "birthdate": "2012-02-03",
  "biography": "fff",
  "city": "fff",
  "password": "123"
}

###
POST {{protocol}}{{host}}/login
Content-Type: application/json

{
  "id": "a8a185d9-cc6f-4bb0-91f7-7f3347aed752",
  "password": "123"
}

###
GET {{protocol}}{{host}}/user/get/f33cb6dd-dad0-4fc8-8511-fbecc91dc2bc
Content-Type: application/json
