version: '3.8'

services:
  postgres-otus-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /tmp
    volumes:
      - ./01-schema-init.sql:/docker-entrypoint-initdb.d/init.sql

  otus-highload-hw1-reactive:
    image: recvezitor/otus-highload-hw1-reactive:latest
    depends_on:
      - postgres-otus-db
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgresql://postgres-otus-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_POOL_SIZE: 100
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1024M"
        reservations:
          cpus: "0.5"
          memory: "128M"
